hikinglocation/config/routes.rb
Rails.application.routes.draw do
 root :to => redirect('/login')
  get 'users/new'

  resources :users
  resources :apikeys
  resource :admins

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout
  

  

  
  
  
  
  

end

hikinglocation/app/models/apikey.rb
class Apikey < ActiveRecord::Base
  belongs_to :user
  attr_accessor :tmp_user_id

  before_validation { self.key = Array.new(30){rand(36).to_s(36)}.join.upcase}
  before_validation { set_user }
  before_save { self.device = device.downcase }
  
  validates :key, presence: true, uniqueness: true
  validates :user_id, presence: true
  validates :device, presence: {:message => "Please Enter!"}, length: {maximum: 30}

  def set_user
    if User.find_by(id: tmp_user_id) &&  tmp_user_id
      self.user_id = tmp_user_id
    end
  end
end

hikinglocation/app/models/location.rb
class Location < ActiveRecord::Base
end

hikinglocation/app/models/story.rb
class Story < ActiveRecord::Base
end

hikinglocation/app/models/tag.rb
class Tag < ActiveRecord::Base
end

hikinglocation/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :apikeys

  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: {:message => "is required!"}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :username, presence: {:message => "is required!"}, length:  { maximum: 15 }, uniqueness:  { case_sensitive: false }
end

hikinglocation/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :check_user, only: [:show, :destroy]

  def show
    @user = User.all
  end

  def destroy
    @destroyUser = User.find_by(id: params[:id])

    if @destroyUser
      @destroyUser.destroy
      flash[:success] = "Removed User!"
    else
      flash[:danger] = "User does not exit!"
    end

    redirect_to admins_path
  end
end

hikinglocation/app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < ApplicationController
    
    
    def index
        
    end
    
    def show
        
    end
end

hikinglocation/app/controllers/api/v1/stories_controller.rb
class Api::V1::StoriesController < ApplicationController
    
    
    def create
    
    end
    
    
    
    def update
    
    end
    
    def destroy
    
    end
    
    def index
    
    end
    
    def show
   
    end
    
    private
    
    def story_params
      
    end
end

hikinglocation/app/controllers/api/v1/tags_controller.rb
class Api::V1::TagsController < ApplicationController
    
    
    def show
    
    end
    
    def index
    
    end
    
    
end

hikinglocation/app/controllers/apikeys_controller.rb
class ApikeysController < ApplicationController
  before_action :check_user, only: [:index, :new, :create, :destroy]
  
  def new
    @apikey = Apikey.new
  end

  def index
    @user = User.find_by(id: session[:user_id])
  end

  def create
    @apikey = Apikey.new(api_key_params)
    @apikey.tmp_user_id = session[:user_id]

    if @apikey.save
      flash[:success] = "API key was created"
      redirect_to apikeys_path
    else
      render :action => 'new'
    end
  end

  def destroy
    @apikey = Apikey.find_by(id: params[:id])
    if @apikey
      @apikey.destroy
    end
    flash[:danger] = "API key was removed"
    redirect_user
  end

  private
  def api_key_params
    params.require(:apikey).permit(:device)
  end
end

hikinglocation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

hikinglocation/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
    else
      flash.now[:danger] = 'Invalid Email or Password!'
      render 'new'
    end
  end

  def destroy
    logout

    flash[:success] = "You have logged out!"
    redirect_to root_path
  end
end

hikinglocation/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_param)

    if @user.save
      log_in @user
    else
      render :action => 'new'
    end
  end

  private
  def user_param
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

hikinglocation/app/helpers/admins_helper.rb
module AdminsHelper
end

hikinglocation/app/helpers/api/v1/locations_helper.rb
module Api::V1::LocationsHelper
end

hikinglocation/app/helpers/api/v1/stories_helper.rb
module Api::V1::StoriesHelper
end

hikinglocation/app/helpers/api/v1/tags_helper.rb
module Api::V1::TagsHelper
end

hikinglocation/app/helpers/apikeys_helper.rb
module ApikeysHelper
end

hikinglocation/app/helpers/application_helper.rb
module ApplicationHelper
end

hikinglocation/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    session[:username] = user.username
    redirect_user
  end

  def logout
    session.delete(:user_id)
    session.delete(:username)
    @user_auth = nil
  end

  def redirect_user
    if is_admin?
      redirect_to admins_path
    else
      redirect_to apikeys_path
    end
  end

  def the_current_user
    @user_auth ||= User.find_by(id: session[:user_id])
  end

  def is_admin?
    User.find_by(username: session[:username]) == User.find_by(username: "admin")
  end

  def is_user_logged_in?
    !the_current_user.nil?
  end

  def check_user
    unless is_user_logged_in?
      flash[:danger] = "Login to see your API keys!"
      redirect_to root_path
    end
  end
end

hikinglocation/app/helpers/users_helper.rb
module UsersHelper
end

hikinglocation/app/views/apikeys/index.html.erb
<div class="container">
    <%= link_to "Create APIkey", new_apikey_path %>
    <%= link_to "Log out", logout_path %>
    <p>Signed in</p>
</div>

<table>
  <tr>
    <td>Device</td>
    <td>Key</td>
    <td>Action</td>
  </tr>
  <% @user.apikeys.each do | apikeys | %>
      <tr>
        <td><%= apikeys.device %></td>
        <td><%= apikeys.key %></td>
        <td><%= link_to "Delete key", apikey_path(apikeys.id), method: :delete, data: { confirm: "Are you sure you want to remove this API key?" }%></td>
      </tr>
  <% end %>
</table>

hikinglocation/app/views/apikeys/new.html.erb
<div class="container">
    <%= link_to "Go back", apikeys_path %>
    <p>Create API key</p>
</div>


<% if @apikey.errors.any? %>
    <div>
      <h2>Something went wrong with the registration</h2>

      <ul>
        <% @apikey.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div>
  <div>
    <%= form_for @apikey do | f |%>
        <p><%= f.label :device_name  %></p>
        <p><%= f.text_field :device, placeholder: "Device name" %></p>

        <p><%= f.submit "Create" %></p>
    <% end %>
  </div>
</div>

hikinglocation/app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div>
      <h2>Something went wrong with the registration</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg|%>
          <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div>
  <h1>Webb API</h1>
  <h2>Register</h2>
</div>

<%= link_to "Back", root_path %>
  <div>
    <%= form_for @user do | f |%>
        <p><%= f.label :username %></p>
        <p><%= f.text_field :username, placeholder: "Username" %></p>

        <p><%= f.label :email %></p>
        <p><%= f.email_field :email, placeholder: "Email" %></p>

        <p><%= f.label :password %></p>
        <p><%= f.password_field :password, placeholder: "Password" %></p>

        <p><%= f.label :password_confirmation %></p>
        <p><%= f.password_field :password_confirmation, placeholder: "Password confirmation" %></p>

        <p><%= f.submit "Register" %></p>
    <% end %>
  </div>